---
title: "HJA_fungi_comp_tree"
author: "Kyle Gervers"
date: "February 2, 2019"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(knitr)
library(CoDaSeq)
library(ALDEx2)
library(compositions)
library(zCompositions)
library(igraph)
library(grDevices)
library(car)
library(propr)
library(grid)
library(tidyverse)
library(magrittr)
library(phyloseq)
library(ggthemes)
library(ggplot2)
library(vegan)
library(metagMisc)

source("C:/Users/gerve/Desktop/PhD/Projects/DF_MiSeq/CoDaSeq-master/chunk/codaSeq_functions.R")

setwd("C:/Users/gerve/Desktop/PhD/Projects/DF_MiSeq/data/scratch/")
```

```{r}
needle <- function(x) {
  needle.fungi.hja.phy <- subset_taxa(x, Kingdom == "k__Fungi") %>% subset_samples(Control == "No" & Organ == "Needle")
  
  needle.fungi.hja.phy %<>% prune_samples(sample_sums(.) > min.reads,.) %>% filter_taxa(function(x) {sum(x) > 0}, TRUE)
  
  t.needle.fungi.hja.otu <- otu_table(needle.fungi.hja.phy) %>% t()
  
  cutoff.denom <- nsamples(needle.fungi.hja.phy)
  
  min.reads <- 70 #minimum reads per sample
  min.prop <- 0.001 #minimum proportion abudance of an OTU in any sample
  cutoff <- 2/cutoff.denom #minimum proportion of occurrences of OTU among all samples--probably too high for these data!
  
  keep.t.needle.fungi.hja.otu <- codaSeq.filter(t.needle.fungi.hja.otu, min.reads = min.reads, min.prop=min.prop, min.occurrence = cutoff, samples.by.row=FALSE)
  
  gbm.needle.fungi.hja.otu <- cmultRepl(t(keep.t.needle.fungi.hja.otu), label=0, method="GBM")
  
  #czm.needle.fungi.hja.otu <- cmultRepl(t(keep.t.needle.fungi.hja.otu), label=0, method="CZM")
  #there have been some issues when "method" is set to "GBM"
  #only "CZM" appears to work
  
  clr.gbm.needle.fungi.hja.otu <- codaSeq.clr(gbm.needle.fungi.hja.otu, samples.by.row=TRUE)
  
  #clr.czm.needle.fungi.hja.otu <- codaSeq.clr(czm.needle.fungi.hja.otu, samples.by.row=TRUE)
  #the success of this step seems to largely depend on the choice of cutoff value--i.e. it simply was not working at cutoff = 0.01
  
  otu_table(needle.fungi.hja.phy) <- otu_table(clr.gbm.needle.fungi.hja.otu, taxa_are_rows = FALSE)
  
  #otu_table(needle.fungi.hja.phy) <- otu_table(clr.czm.needle.fungi.hja.otu, taxa_are_rows = FALSE)
  
  #needle.fungi.hja.meta <- needle.fungi.hja.phy %>% sample_data() %>% data.frame()
  
  #needle.fungi.hja.euc <- phyloseq::distance(needle.fungi.hja.phy, "euclidean")
  
  #adonis(needle.fungi.hja.euc ~ Age + Height, data = needle.fungi.hja.meta) %>% print()
  
  #height.needle.fungi.hja.bdisp <- betadisper(needle.fungi.hja.euc,needle.fungi.hja.meta$Height)
  
  #height.needle.fungi.hja.bdisp %>% anova() %>% print()
  
  #age.needle.fungi.hja.bdisp <- betadisper(needle.fungi.hja.euc,needle.fungi.hja.meta$Age)
  
  #age.needle.fungi.hja.bdisp %>% anova() %>% print()
  
  return(needle.fungi.hja.phy)
  
}
```

```{r}
twig <- function(x) {
  twig.fungi.hja.phy <- subset_taxa(x, Kingdom == "k__Fungi") %>% subset_samples(Control == "No" & Organ == "Twig")
  
  twig.fungi.hja.phy %<>% prune_samples(sample_sums(.) > min.reads,.) %>% filter_taxa(function(x) {sum(x) > 0}, TRUE)
  
  t.twig.fungi.hja.otu <- otu_table(twig.fungi.hja.phy) %>% t()
  
  cutoff.denom <- nsamples(twig.fungi.hja.phy)
  
  min.reads <- 70 #minimum reads per sample
  min.prop <- 0.001 #minimum proportion abudance of an OTU in any sample
  cutoff <- 1/cutoff.denom #minimum proportion of occurrences of OTU among all samples--probably too high for these data!
  
  keep.t.twig.fungi.hja.otu <- codaSeq.filter(t.twig.fungi.hja.otu, min.reads = min.reads, min.prop=min.prop, min.occurrence = cutoff, samples.by.row=FALSE)
  
  #gbm.twig.fungi.hja.otu <- cmultRepl(t(keep.t.twig.fungi.hja.otu), label=0, method="GBM")
  
  czm.twig.fungi.hja.otu <- cmultRepl(t(keep.t.twig.fungi.hja.otu), label=0, method="CZM")
  #there have been some issues when "method" is set to "GBM"
  #only "CZM" appears to work
  
  #clr.gbm.twig.fungi.hja.otu <- codaSeq.clr(gbm.twig.fungi.hja.otu, samples.by.row=TRUE)
  
  clr.czm.twig.fungi.hja.otu <- codaSeq.clr(czm.twig.fungi.hja.otu, samples.by.row=TRUE)
  #the success of this step seems to largely depend on the choice of cutoff value--i.e. it simply was not working at cutoff = 0.01
  
  #otu_table(twig.fungi.hja.phy) <- otu_table(clr.gbm.twig.fungi.hja.otu, taxa_are_rows = FALSE)
  
  otu_table(twig.fungi.hja.phy) <- otu_table(clr.czm.twig.fungi.hja.otu, taxa_are_rows = FALSE)
  
  #twig.fungi.hja.meta <- twig.fungi.hja.phy %>% sample_data() %>% data.frame()
  
  #twig.fungi.hja.euc <- phyloseq::distance(twig.fungi.hja.phy, "euclidean")
  
  #height.twig.fungi.hja.bdisp <- betadisper(twig.fungi.hja.euc,twig.fungi.hja.meta$Height)
  #height.twig.fungi.hja.bdisp %>% anova() %>% print()
  
  return(twig.fungi.hja.phy)
}  
```

```{r}
pcoa.needle <- function(x){
  
  #ht_title <- paste(sample_data(x)$Tree," needle sample composition by height")
  canopy_title <- paste(sample_data(x)$Tree," needle sample composition by canopy level")
  #age_title <- paste(sample_data(x)$Tree," needle sample composition by age")
  
  pcoa.needle.fungi.hja.ord <- ordinate(x, "PCoA", "euclidean")
  #nmds.needle.fungi.hja.ord <- ordinate(x, "NMDS", "euclidean", trymax = 150)

  #height.pcoa.needle.fungi.hja.ord.plot <- plot_ordination(x, pcoa.needle.fungi.hja.ord, type = "samples", color = "Height")
  #age.pcoa.needle.fungi.hja.ord.plot <- plot_ordination(x, pcoa.needle.fungi.hja.ord, type = "samples", shape = "Age", color = "Age")
  canopy.pcoa.needle.fungi.hja.ord.plot <- plot_ordination(x, pcoa.needle.fungi.hja.ord, type = "samples", shape ="CanopyLevel", color = "CanopyLevel")
  
  #height.pcoa.needle.fungi.hja.ord.plot + geom_point(size=5) + scale_fill_gradient2(midpoint = 3) + ggtitle(paste(ht_title))
  canopy.pcoa.needle.fungi.hja.ord.plot + geom_point(size=5) + ggtitle(paste(canopy_title))
  #age.pcoa.needle.fungi.hja.ord.plot + geom_point(size=5) + ggtitle(paste(age_title))
  
  #height.nmds.needle.fungi.hja.ord.plot <- plot_ordination(x, nmds.needle.fungi.hja.ord, type = "samples", color = "Height")
  #age.nmds.needle.fungi.hja.ord.plot <- plot_ordination(x, nmds.needle.fungi.hja.ord, type = "samples", shape = "Age", color = "Age")
  #canopy.nmds.needle.fungi.hja.ord.plot <- plot_ordination(x, nmds.needle.fungi.hja.ord, type = "samples", shape ="CanopyLevel", color = "CanopyLevel")

  #height.nmds.needle.fungi.hja.ord.plot + geom_point(size=5) + scale_fill_gradient2(midpoint = 3) + ggtitle(paste(ht_title))
  #canopy.nmds.needle.fungi.hja.ord.plot + geom_point(size=5) + ggtitle(paste(canopy_title))
  #age.nmds.needle.fungi.hja.ord.plot + geom_point(size=5) + ggtitle(paste(age_title))
  
}

```

```{r}
pcoa.twig <- function(x){
  
  #ht_title <- paste(sample_data(x)$Tree," twig sample composition by height")
  canopy_title <- paste(sample_data(x)$Tree," twig sample composition by canopy level")
  #age_title <- paste(sample_data(x)$Tree," twig sample composition by age")

  pcoa.twig.fungi.hja.ord <- ordinate(x, "PCoA", "euclidean")
  #nmds.twig.fungi.hja.ord <- ordinate(x, "NMDS", "euclidean", trymax = 150)

  #height.pcoa.twig.fungi.hja.ord.plot <- plot_ordination(x, pcoa.twig.fungi.hja.ord, type = "samples", color = "Height")
  #age.pcoa.twig.fungi.hja.ord.plot <- plot_ordination(x, pcoa.twig.fungi.hja.ord, type = "samples", shape = "Age", color = "Age")
  canopy.pcoa.twig.fungi.hja.ord.plot <- plot_ordination(x, pcoa.twig.fungi.hja.ord, type = "samples", shape ="CanopyLevel", color = "CanopyLevel")

  #height.pcoa.twig.fungi.hja.ord.plot + geom_point(size=5) + scale_fill_gradient2(midpoint = 3) + ggtitle(paste(ht_title))
  canopy.pcoa.twig.fungi.hja.ord.plot + geom_point(size=5) + ggtitle(paste(canopy_title))
  #age.pcoa.twig.fungi.hja.ord.plot + geom_point(size=5) + ggtitle(paste(age_title))
  
  #height.nmds.twig.fungi.hja.ord.plot <- plot_ordination(x, nmds.twig.fungi.hja.ord, type = "samples", color = "Height")
  #age.nmds.twig.fungi.hja.ord.plot <- plot_ordination(x, nmds.twig.fungi.hja.ord, type = "samples", shape = "Age", color = "Age")
  #canopy.nmds.twig.fungi.hja.ord.plot <- plot_ordination(x, nmds.twig.fungi.hja.ord, type = "samples", shape ="CanopyLevel", color = "CanopyLevel")

  #height.nmds.twig.fungi.hja.ord.plot + geom_point(size=5) + scale_fill_gradient2(midpoint = 3) + ggtitle(paste(ht_title))
  #canopy.nmds.twig.fungi.hja.ord.plot + geom_point(size=5) + ggtitle(paste(canopy_title))
  #age.nmds.twig.fungi.hja.ord.plot + geom_point(size=5) + ggtitle(paste(age_title))

}
```

```{r}
hja.phy <- readRDS("./HJA.fungi.phy.tax.rds")

hja.meta <- read.csv("./HJA_metadata.csv",as.is=T,row.names=1)
sample_data(hja.phy) <- hja.meta

sample_data(hja.phy)$Height %<>% as.numeric()
sample_data(hja.phy)$CanopyLevel %<>% as.factor()
sample_data(hja.phy)$X %<>% as.numeric()
sample_data(hja.phy)$Y %<>% as.numeric()
sample_data(hja.phy)$Tree %<>% as.factor()
sample_data(hja.phy)$Age %<>% as.factor()
sample_data(hja.phy)$Organ %<>% as.factor()
sample_data(hja.phy)$Early %<>% as.factor()
sample_data(hja.phy)$Plate %<>% as.factor()
sample_data(hja.phy)$Control %<>% as.factor()

#applying the above should probably be done after splitting samples by organ--the latter seems like it could be problematic
#you might still want to have the option to look at taxa shared in both tissues

hja.phy.split <- phyloseq_sep_variable(hja.phy, "Tree", drop_zeroes = F)
hja.phy.split[[1]] <- NULL
#hja.phy.split[[2]] <- NULL #toggle these on and off if you want twigs or needles

tree.needle <- lapply(hja.phy.split, needle) #toggle these on and off if you want needles or twigs
lapply(tree.needle, pcoa.needle) #toggle these on and off if you want needles or twigs

#tree.twig <- lapply(hja.phy.split, twig)
#lapply(tree.twig, pcoa.twig)
```